CAMERA_INDEX = 0
MODEL_NAME = 'ArcFace'
DETECTOR_BACKEND = 'mtcnn'
DISTANCE_METRIC = 'cosine'
VERIFICATION_THRESHOLD = 0.28
LIVENESS_THRESHOLD = 0.70 
LIVENESS_MODEL_PATH = 'src/public/weights/2.7_80x80_MiniFASNetV2.pth'
